name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore dependencies
        run: dotnet restore ./src/Docplanner.Api.sln

      - name: Build
        run: dotnet build ./src/Docplanner.Api.sln --no-restore --configuration Release

      - name: Run Unit Tests
        run: dotnet test ./src/Docplanner.ApiTests.Unit/Docplanner.ApiTests.Unit.csproj --configuration Release --no-build --verbosity normal

      - name: Run Integration Tests
        run: dotnet test ./src/Docplanner.ApiTests.Integration/Docplanner.ApiTests.Integration.csproj --configuration Release --no-build --verbosity normal
